import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./styles.css";
import "./character.css";
import "./character-render-fix.css";
import "./till-blond.css";
import "./task-detail.css";
import "./workflow-restore.css";
import "./mischief-v2.css";
import "./till-visibility.css";
ReactDOM.createRoot(document.getElementById("root")).render(<React.StrictMode><App /></React.StrictMode>);
